name: CI

on:
  push:         { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # ───────────── checkout (incl. submodules) ─────────────
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # ───────────── system dependencies ─────────────────────
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake git \
          gdal-bin libgdal-dev \
          libtiff5-dev nlohmann-json3-dev

    # ───────────── configure & build everything ────────────
    - name: Configure CMake
      run: cmake -S mempa/algorithm -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build (app + unit tests)
      run: cmake --build build --parallel

    # ───────────── test data ───────────────────────────────
    - name: Download Mars DEM .tif
      run: |
        mkdir -p mempa/algorithm/tests
        curl -L https://planetarymaps.usgs.gov/mosaic/Mars/THEMIS_controlled_mosaics/SinusSabaeus_DayIR_31Jan2014/THEMIS_DayIR_ControlledMosaic_SinusSabaeus_30S00E_100mpp.tif \
             -o mempa/algorithm/tests/mars_dem.tif

    # ───────────── run unit tests ──────────────────────────
    - name: Run tests
      run: ctest --test-dir build --output-on-failure
      env:
        PRINT_OUTPUT: "false"

    # ───────────── clean (optional) ────────────────────────
    - name: Clean build directory
      run: cmake --build build --target clean
