name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gdal-bin libgdal-dev libtiff5-dev cmake git nlohmann-json3-dev

    - name: Build the main program
      run: |
        make
      working-directory: mempa/algorithm

    - name: Download smaller Mars DEM for faster testing
      run: |
        mkdir -p mempa/tests
        # Download the 2GB MOLA DEM file instead of the larger one
        curl -L https://planetarymaps.usgs.gov/mosaic/Mars_MGS_MOLA_DEM_mosaic_global_463m.tif -o mars_dem.tif
      working-directory: mempa/algorithm/tests
      
    - name: Clip DEM to test region
      run: |
        # Clip to Olympus Mons region for even faster testing
        gdal_translate -projwin 0 0 480 560 mars_dem.tif mars_clipped.tif
        # Replace original with smaller clipped version
        mv mars_clipped.tif mars_dem.tif
      working-directory: mempa/algorithm/tests

    - name: Build and run tests
      run: |
        make test
      env:
        PRINT_OUTPUT: "false"
      working-directory: mempa/algorithm

    - name: Clean up
      run: |
        make clean
      working-directory: mempa/algorithm