name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ gdal-bin libgdal-dev libtiff5-dev cmake git nlohmann-json3-dev

      - name: Configure with CMake
        run: cmake -S . -B build
        working-directory: mempa/algorithm

      - name: Build
        run: cmake --build build -- -j$(nproc)
        working-directory: mempa/algorithm

      - name: Download Mars DEM .tif
        run: |
          mkdir -p mempa/algorithm/tests
          curl -L \
            https://planetarymaps.usgs.gov/mosaic/Mars/THEMIS_controlled_mosaics/SinusSabaeus_DayIR_31Jan2014/THEMIS_DayIR_ControlledMosaic_SinusSabaeus_30S00E_100mpp.tif \
            -o build/tests/mars_dem.tif
        working-directory: mempa/algorithm

      - name: Run tests
        run: cmake --build build --target test
        working-directory: mempa/algorithm

      - name: Clean up
        run: rm -rf build
        working-directory: mempa/algorithm