name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gdal-bin libgdal-dev libtiff5-dev cmake git nlohmann-json3-dev

    - name: Build the main program
      run: |
        make
      working-directory: mempa/algorithm

    - name: Download Mars DEM .tif
      run: |
        mkdir -p mempa/tests
        curl -L https://planetarymaps.usgs.gov/mosaic/Mars/THEMIS_controlled_mosaics/SinusSabaeus_DayIR_31Jan2014/THEMIS_DayIR_ControlledMosaic_SinusSabaeus_30S00E_100mpp.tif -o mars_dem.tif
      working-directory: mempa/algorithm/tests

    - name: Build and run tests
      run: |
        make test
      env:
        PRINT_OUTPUT: "false"
      working-directory: mempa/algorithm

    - name: Clean up
      run: |
        make clean
      working-directory: mempa/algorithm

  build-and-test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict

    - name: Install GDAL
      run: conda install -y gdal
      shell: powershell

    - name: Download nlohmann/json single-header
      run: |
        mkdir -p deps/json
        curl -L https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp -o deps/json/json.hpp
      shell: bash

    - name: Build the main program
      run: |
        make
      shell: bash
      working-directory: mempa/algorithm

    - name: Download Mars DEM .tif
      run: |
        mkdir -p mempa/tests
        curl -L https://planetarymaps.usgs.gov/mosaic/Mars/THEMIS_controlled_mosaics/SinusSabaeus_DayIR_31Jan2014/THEMIS_DayIR_ControlledMosaic_SinusSabaeus_30S00E_100mpp.tif -o mars_dem.tif
      shell: bash
      working-directory: mempa/algorithm/tests

    - name: Build and run tests
      run: |
        make test
      env:
        PRINT_OUTPUT: "false"
      shell: bash
      working-directory: mempa/algorithm

    - name: Clean up
      run: |
        make clean
      shell: bash
      working-directory: mempa/algorithm
