name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ gdal-bin libgdal-dev libtiff5-dev \
            cmake git nlohmann-json3-dev

      - name: Configure CMake
        run: cmake -S mempa/algorithm -B build -DCMAKE_BUILD_TYPE=Release

      - name: Download Mars DEM .tif
        run: |
          mkdir -p mempa/algorithm/tests
          curl -L \
            https://planetarymaps.usgs.gov/mosaic/Mars/THEMIS_controlled_mosaics/SinusSabaeus_DayIR_31Jan2014/THEMIS_DayIR_ControlledMosaic_SinusSabaeus_30S00E_100mpp.tif \
            -o mempa/algorithm/tests/mars_dem.tif

      - name: Build + run tests
        run: cmake --build build --target check --parallel
        env:
          PRINT_OUTPUT: "false"

      - name: Clean up
        run: cmake --build build --target clean
